#:schema node_modules/wrangler/config-schema.json
name = "remix-workers-app"
compatibility_date = "2024-09-25"

main = "./dist/index.js"
assets = { directory = "./public" }

build.command = "npm run typegen"

[observability]
enabled = true
